name: Build

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build --config Release

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: install xcb dep
        run: |
          sudo apt-get update
          sudo apt-get install libxcb1-dev -y

      - name: install GL libraries
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libegl1-mesa-dev -y

      - name: Configure
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build --config Release
